### PR TITLE
Blockchain Fiesta in Krakow, Poland

### PR DESCRIPTION
**Pull request by artikozel**

### CODE REVIEW

**Comment by xaur** [comment]
@artikozel thanks for the PR, this is awesome. I only suggest to 1) restrict to ASCII character set in filenames (no chars like `ó`), 2) convert to proper markdown (use `*` for bullets, add `.md` extension).

**Comment by artikozel** [comment]
Hi!

I'm glad to contribute. Naturally, I will take your advice to heart and
improve. Please understand that these are my first baby steps into GitHub.

Regards,
Kozel

**Comment by xaur** [comment]
@artikozel there are a few markdown nits: make sure all bullet lists have a newline before and after them, replace tab character with space character.

However, this can be polished later imo. @heyvj can you merge this?

**Comment by artikozel** [comment]
@xaur
Yeah, sorry about that; my markdown is a WIP.

**Comment by heyvj** [comment]
Nice work @artikozel and thanks for reviewing @xaur. Merging!

**Comment by xaur** [comment]
@heyvj please use suqash merges next time, all the intermediate commits do not make much sense on the master branch.

**Pull request merged**
